
package com.pmsc.warning.client;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "FileShareService", targetNamespace = "http://service.warning.pmsc.com/", wsdlLocation = "http://fabu.12379.gov.cn:8080/WarningFileShare/WarnFileService?wsdl")
public class FileShareService
    extends Service
{

    private final static URL FILESHARESERVICE_WSDL_LOCATION;
    private final static WebServiceException FILESHARESERVICE_EXCEPTION;
    private final static QName FILESHARESERVICE_QNAME = new QName("http://service.warning.pmsc.com/", "FileShareService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://fabu.12379.gov.cn:8080/WarningFileShare/WarnFileService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        FILESHARESERVICE_WSDL_LOCATION = url;
        FILESHARESERVICE_EXCEPTION = e;
    }

    public FileShareService() {
        super(__getWsdlLocation(), FILESHARESERVICE_QNAME);
    }

    public FileShareService(WebServiceFeature... features) {
        super(__getWsdlLocation(), FILESHARESERVICE_QNAME, features);
    }

    public FileShareService(URL wsdlLocation) {
        super(wsdlLocation, FILESHARESERVICE_QNAME);
    }

    public FileShareService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, FILESHARESERVICE_QNAME, features);
    }

    public FileShareService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public FileShareService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns FileShare
     */
    @WebEndpoint(name = "FileSharePort")
    public FileShare getFileSharePort() {
        return super.getPort(new QName("http://service.warning.pmsc.com/", "FileSharePort"), FileShare.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns FileShare
     */
    @WebEndpoint(name = "FileSharePort")
    public FileShare getFileSharePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://service.warning.pmsc.com/", "FileSharePort"), FileShare.class, features);
    }

    private static URL __getWsdlLocation() {
        if (FILESHARESERVICE_EXCEPTION!= null) {
            throw FILESHARESERVICE_EXCEPTION;
        }
        return FILESHARESERVICE_WSDL_LOCATION;
    }

}
