
package com.pmsc.warning.service;

import java.util.List;
import javax.activation.DataHandler;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "FileShare", targetNamespace = "http://service.warning.pmsc.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface FileShare {


    /**
     * 
     * @return
     *     returns int
     * @throws SQLException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getMaxWarnId", targetNamespace = "http://service.warning.pmsc.com/", className = "com.pmsc.warning.service.GetMaxWarnId")
    @ResponseWrapper(localName = "getMaxWarnIdResponse", targetNamespace = "http://service.warning.pmsc.com/", className = "com.pmsc.warning.service.GetMaxWarnIdResponse")
    public int getMaxWarnId()
        throws SQLException_Exception
    ;

    /**
     * 
     * @return
     *     returns java.util.List<com.pmsc.warning.service.WarnCap>
     * @throws SQLException_Exception
     */
    @WebMethod(operationName = "ListWarnCap")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "ListWarnCap", targetNamespace = "http://service.warning.pmsc.com/", className = "com.pmsc.warning.service.ListWarnCap")
    @ResponseWrapper(localName = "ListWarnCapResponse", targetNamespace = "http://service.warning.pmsc.com/", className = "com.pmsc.warning.service.ListWarnCapResponse")
    public List<WarnCap> listWarnCap()
        throws SQLException_Exception
    ;

    /**
     * 
     * @param fileName
     * @return
     *     returns javax.activation.DataHandler
     * @throws FileNotFoundException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "download", targetNamespace = "http://service.warning.pmsc.com/", className = "com.pmsc.warning.service.Download")
    @ResponseWrapper(localName = "downloadResponse", targetNamespace = "http://service.warning.pmsc.com/", className = "com.pmsc.warning.service.DownloadResponse")
    public DataHandler download(
        @WebParam(name = "fileName", targetNamespace = "")
        String fileName)
        throws FileNotFoundException_Exception
    ;

    /**
     * 
     * @return
     *     returns java.util.List<java.lang.String>
     * @throws SQLException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "listWarnEvent", targetNamespace = "http://service.warning.pmsc.com/", className = "com.pmsc.warning.service.ListWarnEvent")
    @ResponseWrapper(localName = "listWarnEventResponse", targetNamespace = "http://service.warning.pmsc.com/", className = "com.pmsc.warning.service.ListWarnEventResponse")
    public List<String> listWarnEvent()
        throws SQLException_Exception
    ;

    /**
     * 
     * @return
     *     returns java.util.List<java.lang.String>
     * @throws SQLException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "listFiles", targetNamespace = "http://service.warning.pmsc.com/", className = "com.pmsc.warning.service.ListFiles")
    @ResponseWrapper(localName = "listFilesResponse", targetNamespace = "http://service.warning.pmsc.com/", className = "com.pmsc.warning.service.ListFilesResponse")
    public List<String> listFiles()
        throws SQLException_Exception
    ;

    /**
     * 
     * @return
     *     returns java.util.List<java.lang.String>
     * @throws SQLException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "listWarnRegionInfo", targetNamespace = "http://service.warning.pmsc.com/", className = "com.pmsc.warning.service.ListWarnRegionInfo")
    @ResponseWrapper(localName = "listWarnRegionInfoResponse", targetNamespace = "http://service.warning.pmsc.com/", className = "com.pmsc.warning.service.ListWarnRegionInfoResponse")
    public List<String> listWarnRegionInfo()
        throws SQLException_Exception
    ;

    /**
     * 
     * @param areaCode
     * @param warnLevel
     * @param itime
     * @param warnEvent
     * @return
     *     returns java.util.List<java.lang.String>
     * @throws SQLException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "listFilesByElement", targetNamespace = "http://service.warning.pmsc.com/", className = "com.pmsc.warning.service.ListFilesByElement")
    @ResponseWrapper(localName = "listFilesByElementResponse", targetNamespace = "http://service.warning.pmsc.com/", className = "com.pmsc.warning.service.ListFilesByElementResponse")
    public List<String> listFilesByElement(
        @WebParam(name = "areaCode", targetNamespace = "")
        String areaCode,
        @WebParam(name = "warnLevel", targetNamespace = "")
        String warnLevel,
        @WebParam(name = "warnEvent", targetNamespace = "")
        String warnEvent,
        @WebParam(name = "itime", targetNamespace = "")
        int itime)
        throws SQLException_Exception
    ;

    /**
     * 
     * @param record
     * @return
     *     returns java.util.List<java.lang.String>
     * @throws SQLException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "listFilesByTop", targetNamespace = "http://service.warning.pmsc.com/", className = "com.pmsc.warning.service.ListFilesByTop")
    @ResponseWrapper(localName = "listFilesByTopResponse", targetNamespace = "http://service.warning.pmsc.com/", className = "com.pmsc.warning.service.ListFilesByTopResponse")
    public List<String> listFilesByTop(
        @WebParam(name = "record", targetNamespace = "")
        int record)
        throws SQLException_Exception
    ;

    /**
     * 
     * @param areaCode
     * @param warnLevel
     * @param itime
     * @param warnEvent
     * @return
     *     returns java.util.List<com.pmsc.warning.service.WarnCap>
     * @throws SQLException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "listWarnCapByElement", targetNamespace = "http://service.warning.pmsc.com/", className = "com.pmsc.warning.service.ListWarnCapByElement")
    @ResponseWrapper(localName = "listWarnCapByElementResponse", targetNamespace = "http://service.warning.pmsc.com/", className = "com.pmsc.warning.service.ListWarnCapByElementResponse")
    public List<WarnCap> listWarnCapByElement(
        @WebParam(name = "areaCode", targetNamespace = "")
        String areaCode,
        @WebParam(name = "warnLevel", targetNamespace = "")
        String warnLevel,
        @WebParam(name = "warnEvent", targetNamespace = "")
        String warnEvent,
        @WebParam(name = "itime", targetNamespace = "")
        int itime)
        throws SQLException_Exception
    ;

    /**
     * 
     * @param warnId
     * @return
     *     returns java.util.List<java.lang.String>
     * @throws SQLException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "listFilesByWarnId", targetNamespace = "http://service.warning.pmsc.com/", className = "com.pmsc.warning.service.ListFilesByWarnId")
    @ResponseWrapper(localName = "listFilesByWarnIdResponse", targetNamespace = "http://service.warning.pmsc.com/", className = "com.pmsc.warning.service.ListFilesByWarnIdResponse")
    public List<String> listFilesByWarnId(
        @WebParam(name = "warnId", targetNamespace = "")
        int warnId)
        throws SQLException_Exception
    ;

}
