package com.pmsc.warning;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.0.1
 * 2017-02-14T09:51:30.076+08:00
 * Generated source version: 3.0.1
 * 
 */
@WebService(targetNamespace = "http://service.warning.pmsc.com/", name = "FileShare")
@XmlSeeAlso({ObjectFactory.class})
public interface FileShare {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "download", targetNamespace = "http://service.warning.pmsc.com/", className = "com.pmsc.warning.Download")
    @WebMethod
    @ResponseWrapper(localName = "downloadResponse", targetNamespace = "http://service.warning.pmsc.com/", className = "com.pmsc.warning.DownloadResponse")
    public javax.activation.DataHandler download(
        @WebParam(name = "fileName", targetNamespace = "")
        java.lang.String fileName
    ) throws FileNotFoundException_Exception;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "listFiles", targetNamespace = "http://service.warning.pmsc.com/", className = "com.pmsc.warning.ListFiles")
    @WebMethod
    @ResponseWrapper(localName = "listFilesResponse", targetNamespace = "http://service.warning.pmsc.com/", className = "com.pmsc.warning.ListFilesResponse")
    public java.util.List<java.lang.String> listFiles() throws SQLException_Exception;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "listWarnEvent", targetNamespace = "http://service.warning.pmsc.com/", className = "com.pmsc.warning.ListWarnEvent")
    @WebMethod
    @ResponseWrapper(localName = "listWarnEventResponse", targetNamespace = "http://service.warning.pmsc.com/", className = "com.pmsc.warning.ListWarnEventResponse")
    public java.util.List<java.lang.String> listWarnEvent() throws SQLException_Exception;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getMaxWarnId", targetNamespace = "http://service.warning.pmsc.com/", className = "com.pmsc.warning.GetMaxWarnId")
    @WebMethod
    @ResponseWrapper(localName = "getMaxWarnIdResponse", targetNamespace = "http://service.warning.pmsc.com/", className = "com.pmsc.warning.GetMaxWarnIdResponse")
    public int getMaxWarnId() throws SQLException_Exception;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "listWarnRegionInfo", targetNamespace = "http://service.warning.pmsc.com/", className = "com.pmsc.warning.ListWarnRegionInfo")
    @WebMethod
    @ResponseWrapper(localName = "listWarnRegionInfoResponse", targetNamespace = "http://service.warning.pmsc.com/", className = "com.pmsc.warning.ListWarnRegionInfoResponse")
    public java.util.List<java.lang.String> listWarnRegionInfo() throws SQLException_Exception;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "ListWarnCap", targetNamespace = "http://service.warning.pmsc.com/", className = "com.pmsc.warning.ListWarnCap")
    @WebMethod(operationName = "ListWarnCap")
    @ResponseWrapper(localName = "ListWarnCapResponse", targetNamespace = "http://service.warning.pmsc.com/", className = "com.pmsc.warning.ListWarnCapResponse")
    public java.util.List<com.pmsc.warning.WarnCap> listWarnCap() throws SQLException_Exception;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "listFilesByWarnId", targetNamespace = "http://service.warning.pmsc.com/", className = "com.pmsc.warning.ListFilesByWarnId")
    @WebMethod
    @ResponseWrapper(localName = "listFilesByWarnIdResponse", targetNamespace = "http://service.warning.pmsc.com/", className = "com.pmsc.warning.ListFilesByWarnIdResponse")
    public java.util.List<java.lang.String> listFilesByWarnId(
        @WebParam(name = "warnId", targetNamespace = "")
        int warnId
    ) throws SQLException_Exception;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "listWarnCapByElement", targetNamespace = "http://service.warning.pmsc.com/", className = "com.pmsc.warning.ListWarnCapByElement")
    @WebMethod
    @ResponseWrapper(localName = "listWarnCapByElementResponse", targetNamespace = "http://service.warning.pmsc.com/", className = "com.pmsc.warning.ListWarnCapByElementResponse")
    public java.util.List<com.pmsc.warning.WarnCap> listWarnCapByElement(
        @WebParam(name = "areaCode", targetNamespace = "")
        java.lang.String areaCode,
        @WebParam(name = "warnLevel", targetNamespace = "")
        java.lang.String warnLevel,
        @WebParam(name = "warnEvent", targetNamespace = "")
        java.lang.String warnEvent,
        @WebParam(name = "itime", targetNamespace = "")
        int itime
    ) throws SQLException_Exception;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "listFilesByTop", targetNamespace = "http://service.warning.pmsc.com/", className = "com.pmsc.warning.ListFilesByTop")
    @WebMethod
    @ResponseWrapper(localName = "listFilesByTopResponse", targetNamespace = "http://service.warning.pmsc.com/", className = "com.pmsc.warning.ListFilesByTopResponse")
    public java.util.List<java.lang.String> listFilesByTop(
        @WebParam(name = "record", targetNamespace = "")
        int record
    ) throws SQLException_Exception;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "listFilesByElement", targetNamespace = "http://service.warning.pmsc.com/", className = "com.pmsc.warning.ListFilesByElement")
    @WebMethod
    @ResponseWrapper(localName = "listFilesByElementResponse", targetNamespace = "http://service.warning.pmsc.com/", className = "com.pmsc.warning.ListFilesByElementResponse")
    public java.util.List<java.lang.String> listFilesByElement(
        @WebParam(name = "areaCode", targetNamespace = "")
        java.lang.String areaCode,
        @WebParam(name = "warnLevel", targetNamespace = "")
        java.lang.String warnLevel,
        @WebParam(name = "warnEvent", targetNamespace = "")
        java.lang.String warnEvent,
        @WebParam(name = "itime", targetNamespace = "")
        int itime
    ) throws SQLException_Exception;
}
