package com.pmsc.warning;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.0.1
 * 2017-02-14T09:51:30.131+08:00
 * Generated source version: 3.0.1
 * 
 */
@WebServiceClient(name = "FileShareService", 
                  wsdlLocation = "http://fabu.12379.gov.cn:8080/WarningShare/WarnService?wsdl",
                  targetNamespace = "http://service.warning.pmsc.com/") 
public class FileShareService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://service.warning.pmsc.com/", "FileShareService");
    public final static QName FileSharePort = new QName("http://service.warning.pmsc.com/", "FileSharePort");
    static {
        URL url = null;
        try {
            url = new URL("http://fabu.12379.gov.cn:8080/WarningShare/WarnService?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(FileShareService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://fabu.12379.gov.cn:8080/WarningShare/WarnService?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public FileShareService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public FileShareService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public FileShareService() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     *
     * @return
     *     returns FileShare
     */
    @WebEndpoint(name = "FileSharePort")
    public FileShare getFileSharePort() {
        return super.getPort(FileSharePort, FileShare.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns FileShare
     */
    @WebEndpoint(name = "FileSharePort")
    public FileShare getFileSharePort(WebServiceFeature... features) {
        return super.getPort(FileSharePort, FileShare.class, features);
    }

}
