
package com.pmsc.warning;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.0.1
 * 2017-02-14T09:51:30.054+08:00
 * Generated source version: 3.0.1
 */

@WebFault(name = "SQLException", targetNamespace = "http://service.warning.pmsc.com/")
public class SQLException_Exception extends Exception {
    
    private com.pmsc.warning.SQLException sqlException;

    public SQLException_Exception() {
        super();
    }
    
    public SQLException_Exception(String message) {
        super(message);
    }
    
    public SQLException_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public SQLException_Exception(String message, com.pmsc.warning.SQLException sqlException) {
        super(message);
        this.sqlException = sqlException;
    }

    public SQLException_Exception(String message, com.pmsc.warning.SQLException sqlException, Throwable cause) {
        super(message, cause);
        this.sqlException = sqlException;
    }

    public com.pmsc.warning.SQLException getFaultInfo() {
        return this.sqlException;
    }
}
